name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Run tree
      run: tree

    - name: Make ex00
      run: make
      working-directory: ex00

    - name: Re-make ex00
      run: make re
      working-directory: ex00

    - name: View contents of ex00
      run: nm -C megaphone
      working-directory: ex00
    
    - name: Run ex00 (No Arg)
      run: ./megaphone > out_1.txt && echo "* LOUD AND UNBEARABLE FEEDBACK NOISE *" > in_1.txt
      working-directory: ex00
    
    - name: diff ex00
      run: diff -s out_1.txt in_1.txt && rm *.txt
      working-directory: ex00

    - name: Run ex00 `shhhhh... I think the students are asleep...`
      run: ./megaphone "shhhhh... I think the students are asleep..." > out_2.txt && echo "SHHHHH... I THINK THE STUDENTS ARE ASLEEP..." > in_2.txt
      working-directory: ex00
    
    - name: diff ex00
      run: diff -s out_2.txt in_2.txt && rm *.txt
      working-directory: ex00

    - name: Run ex00 `Damnit " ! " "Sorry students, I thought this thing was off."`
      run: ./megaphone Damnit " ! " "Sorry students, I thought this thing was off." > out_3.txt && echo "DAMNIT ! SORRY STUDENTS, I THOUGHT THIS THING WAS OFF." > in_3.txt
      working-directory: ex00
    
    - name: diff ex00
      run: diff -s out_3.txt in_3.txt && rm *.txt
      working-directory: ex00
    
    - name: Make ex01
      run: make
      working-directory: ex01

    - name: Re-make ex01
      run: make re
      working-directory: ex01

    - name: View contents of ex01
      run: nm -C phonebook
      working-directory: ex01
    
    - name: Run ex01
      run: echo "ex01 tests require manual interaction!"
      working-directory: ex01

    - name: Make ex02
      run: make
      working-directory: ex02

    - name: Re-make ex02
      run: make re
      working-directory: ex02

    - name: View contents of ex02
      run: nm -C bank
      working-directory: ex02
    
    - name: Run ex02
      run: ./bank | awk '{ print $2 }' > output.log
      working-directory: ex02
    
    - name: Diff ex02 output
      run: cat 19920104_091532.log | awk '{ print $2 }' | diff -s - output.log && rm output.log
      working-directory: ex02
